import re
from pathlib import Path
from random import randint

from loguru import logger


def replace_value(match_obj) -> str:
    value = randint(0, 512)
    logger.debug(f"Replacing value {match_obj.group(2)} with {value}")
    return match_obj.group(1) + f"{value}" + match_obj.group(3)


def add_ijon_log(patch_file: Path):
    pattern = re.compile(
        r'\+(IJON_[A-Z_]+)\s*\('              # +IJON_* (
        r'([^()]*(?:\([^)]*\)[^()]*)*)'       # arg with up to one nested (…) group
        r'\)\s*;\s*/\*\s*PATCHID\s*:\s*(\d+)\s*\*/'
    )
    content = patch_file.read_text()
    new_content = pattern.sub(lambda m: f'+IJON_LOG({m.group(3)});{m.group(1)}({m.group(2)}); /* PATCHID:{m.group(3)} */', content)
    patch_file.write_text(new_content)


def postprocess_patch_file(patch_file: Path):
    """Post-process the patch file generated by AIJon.

    Args:
        patch_file (Path): The path to the AIJon patch file.
    """
    new_contents: list[str] = []
    for line in patch_file.read_text().splitlines():
        if line.startswith("+IJON_CTX"):
            pattern = r"(\+IJON_CTX\(\s*(?:\([^)]*\))?\s*)(\d+)(\s*\);)"
            line = re.sub(pattern, replace_value, line)
        new_contents.append(line)
    patch_file.write_text("\n".join(new_contents) + "\n")


def postprocess_allowlist_file(allow_list_file: Path):
    """Post-process the allowlist file generated by AIJon.

    Args:
        allow_list_file (Path): The path to the AIJon allowlist file.
    """
    new_contents: list[str] = []
    for line in allow_list_file.read_text().splitlines():
        new_line = line.split(":")[-1]
        logger.debug(f"Replacing Allowlist line: {line} with {new_line}")
        new_contents.append(new_line)
    allow_list_file.write_text("\n".join(new_contents) + "\n")


def postprocess_artifacts(aijon_artifact_dir: Path, diff_mode: bool = False):
    """Post-process the artifacts generated by AIJon.

    Args:
        aijon_artifact_dir (Path): The directory containing the AIJon artifacts.
    """
    if diff_mode:
        patch_file = aijon_artifact_dir / "aijon_instrumentation.patch"
        postprocess_patch_file(patch_file)

    allow_list_file = aijon_artifact_dir / "aijon_allowlist.txt"
    postprocess_allowlist_file(allow_list_file)


if __name__ == "__main__":
    patch_contents = """
+IJON_CTX( (int) 1234 ); /* PATCHID:1234 */
+IJON_CTX( 5678 ); /* PATCHID:5678 */
+IJON_CTX(123); /* PATCHID:9876 */
+IJON_CTX(fileOffset); /* PATCHID:5432 */
+IJON_CTX(actions[n+1].SWF_ACTIONRECORD.ActionCode); /* PATCHID:1063 */
+IJON_MAX((unsigned long long)n); /* PATCHID:11153 */
+IJON_MIN((unsigned long long)n); /* PATCHID:10453 */
+IJON_SET((int)maxn); /* PATCHID:9443 */
+IJON_SET((int)n); /* PATCHID:8754 */
+IJON_CMP((unsigned long long)n, (unsigned long long)maxn); /* PATCHID:7862 */
+IJON_CMP((unsigned long long)n, 0); /* PATCHID:7287 */
"""
#     patch_file = Path("/tmp/test.patch")
#     patch_file.write_text(patch_contents)
#     postprocess_patch_file(patch_file)
    patch_file = Path("/tmp/test.patch")
    patch_file.write_text(patch_contents)
    add_ijon_log(patch_file)