#!/bin/bash

set -e
set -u
set -x

if [ "$#" -eq 1 ]; then
    EXP_ID="$1"
elif [ -n "$EXP_ID" ]; then
    EXP_ID="$EXP_ID"
else
    echo "Usage: $0 <experiment_id>"
    echo "Please provide an experiment ID as the first argument or set the EXP_ID environment variable."
    exit 1
fi

TRIAL=${TRIAL:-1}

OSS_FUZZ_PROJECT_DIR="/oss-fuzz"
if [ ! -d "$OSS_FUZZ_PROJECT_DIR" ]; then
	git clone https://github.com/google/oss-fuzz.git /oss-fuzz
fi
HELPER_SCRIPT="$OSS_FUZZ_PROJECT_DIR/infra/helper.py"

NFS_DIR="/shared//aijon_stuff"
if [ ! -d "$NFS_DIR" ]; then
    echo "NFS mounted directory $NFS_DIR does not exist."
    exit 1
fi

BASE_DIR=$(realpath "$(dirname $(readlink -f $0))/../")
PROJECT_NAME=$(grep "^$EXP_ID," $BASE_DIR/experiments/oss_fuzz_coverage_target_mapping.csv | cut -d',' -f2)
SCRIPT_DIR=$(dirname "$(realpath "$0")")
PARSER_SCRIPT="$SCRIPT_DIR/parse_cov_report.py"

OUTPUT_DIR="$NFS_DIR/oss_fuzz_results/$PROJECT_NAME/trial_${TRIAL}"
FUZZING_OUTPUT_DIR="$OUTPUT_DIR/fuzzing"
COVERAGE_ANALYSIS_OUTPUT_DIR="$OUTPUT_DIR/coverage_analysis"
AFL_FUZZING_OUTPUT_DIR="$NFS_DIR/aflplusplus_results/$PROJECT_NAME/trial_${TRIAL}/fuzzing"

mkdir -p "$COVERAGE_ANALYSIS_OUTPUT_DIR"

LOCAL_OUTPUT_DIR="/aijon/oss_fuzz_results/$PROJECT_NAME"
LOCAL_LOG_OUTPUT_DIR="$LOCAL_OUTPUT_DIR/logs"
LOCAL_INSTRUMENTATION_OUTPUT_DIR="$LOCAL_OUTPUT_DIR/instrumentation"
LOCAL_FUZZING_OUTPUT_DIR="$LOCAL_OUTPUT_DIR/fuzzing"
LOCAL_AFL_FUZZING_OUTPUT_DIR="$LOCAL_OUTPUT_DIR/afl_fuzzing"
LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR="$LOCAL_OUTPUT_DIR/coverage_analysis"

mkdir -p "$LOCAL_LOG_OUTPUT_DIR"
mkdir -p "$LOCAL_INSTRUMENTATION_OUTPUT_DIR"
mkdir -p "$LOCAL_FUZZING_OUTPUT_DIR"
mkdir -p "$LOCAL_AFL_FUZZING_OUTPUT_DIR"
mkdir -p "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR"

chown -R 1000:1000 "$LOCAL_OUTPUT_DIR"

python3 "$HELPER_SCRIPT" build_image "$PROJECT_NAME" --pull
python3 "$HELPER_SCRIPT" build_fuzzers --sanitizer coverage "$PROJECT_NAME"

DOCKER_IMAGE_NAME="gcr.io/oss-fuzz/$PROJECT_NAME"

grep "^$EXP_ID," $BASE_DIR/experiments/oss_fuzz_coverage_target_mapping.csv | tr ',' '\n' | tail -n +3 > /tmp/actual_harnesses.txt

rsync -raz "$FUZZING_OUTPUT_DIR/" "$LOCAL_FUZZING_OUTPUT_DIR/"
rsync -raz "$AFL_FUZZING_OUTPUT_DIR/" "$LOCAL_AFL_FUZZING_OUTPUT_DIR/"

while read -r HARNESS; do
    tar -xf "$LOCAL_FUZZING_OUTPUT_DIR/fuzzing_${HARNESS}.tar.gz" -C "$LOCAL_FUZZING_OUTPUT_DIR"
    chown -R "$USER":"$USER" "$LOCAL_FUZZING_OUTPUT_DIR"

    tar -xf "$LOCAL_AFL_FUZZING_OUTPUT_DIR/fuzzing_${HARNESS}.tar.gz" -C "$LOCAL_AFL_FUZZING_OUTPUT_DIR"
    chown -R "$USER":"$USER" "$LOCAL_AFL_FUZZING_OUTPUT_DIR"

    FUZZER_RESULT_DIRECTORY="$LOCAL_FUZZING_OUTPUT_DIR/out/${HARNESS}_afl_address_out"
    AFL_FUZZER_RESULT_DIRECTORY="$LOCAL_AFL_FUZZING_OUTPUT_DIR/${HARNESS}_afl_address_out"

    if [ ! -d "$FUZZER_RESULT_DIRECTORY" ]; then
        echo "Fuzzer result directory $FUZZER_RESULT_DIRECTORY does not exist."
        continue
    fi

    if [ ! -d "$AFL_FUZZER_RESULT_DIRECTORY" ]; then
        echo "AFL Fuzzer result directory $AFL_FUZZER_RESULT_DIRECTORY does not exist."
        continue
    fi

    OUTDIR="$OSS_FUZZ_PROJECT_DIR/build/out/$PROJECT_NAME"
    TEXTCOV_DIR="$OUTDIR/textcov_reports"

    # Create coverage report for the corpus generated by aijon
    CORPUS_DIR="$FUZZER_RESULT_DIRECTORY/default/queue"
    python3 "$HELPER_SCRIPT" coverage --no-serve --fuzz-target "$HARNESS" --corpus-dir "$CORPUS_DIR" "$PROJECT_NAME"
    cp "$TEXTCOV_DIR/${HARNESS}.covreport" "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR/"

    docker run --privileged --rm -v "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR":/coverage_analysis -v "$OUTDIR":/out "$DOCKER_IMAGE_NAME" bash -c "llvm-cov show /out/${HARNESS} -instr-profile=/out/dumps/${HARNESS}.profdata > /coverage_analysis/${HARNESS}.aijon_coverage_txt"

    # Create coverage report for the corpus generated by AFL
    CORPUS_DIR="$AFL_FUZZER_RESULT_DIRECTORY/default/queue"
    python3 "$HELPER_SCRIPT" coverage --no-serve --fuzz-target "$HARNESS" --corpus-dir "$CORPUS_DIR" "$PROJECT_NAME"
    cp "$TEXTCOV_DIR/${HARNESS}.covreport" "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR/${HARNESS}_aflplusplus.covreport"

    docker run --privileged --rm -v "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR":/coverage_analysis -v "$OUTDIR":/out "$DOCKER_IMAGE_NAME" bash -c "llvm-cov show /out/${HARNESS} -instr-profile=/out/dumps/${HARNESS}.profdata > /coverage_analysis/${HARNESS}.afl_coverage_txt"

    python3 "$PARSER_SCRIPT" "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR/${HARNESS}_aflplusplus.covreport" "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR/${HARNESS}.covreport" > "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR/${HARNESS}.comparative_coverage"

done < /tmp/actual_harnesses.txt

cd "$OSS_FUZZ_PROJECT_DIR" && patch -p2 < /tmp/helper.patch && cd -

chown -R 1000:1000 "$LOCAL_OUTPUT_DIR"
tar -czf "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR.tar.gz" -C "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR" .
rsync -raz "$LOCAL_COVERAGE_ANALYSIS_OUTPUT_DIR.tar.gz" "$COVERAGE_ANALYSIS_OUTPUT_DIR/"
